### ISSUE TITLE
Webpack Hot Middleware reloading? 

### ISSUE THREAD

**Issue by edalee** [DigitalKwarts/react-server-render-example#3]
Hi, 
Been following your great article on server-side [rendering](https://blog.digitalkwarts.com/server-side-rendering-with-reactjs-react-router-v4-react-helmet-and-css-modules/), and I'm curious have you got webpack-hot-middleware and webpack-hot-server-middleware working with webpack3?

This seems to be the only difference between your repo and my setup -- yet restarting development.js is the only way to see changes.

**Comment by amerllica** [comment]
Leave the earlier version and get the new one, in the latest version of this example, you have last version of all packages except `webpack`, `webpack` is 3th version not 4th just because of `extract-text-webpack-plugin` conflict with version 4, there is an beta version of `extract-text-webpack-plugin` that is match with `webapck` version 4 but it is not stable.

After `extract-text-webpack-plugin` team release a stable version of 4, I upgrade `webpack` to latest version.
